language: ruby

rvm:
  - 2.3.3

script:
  - bundle exec rake db:create:all
  - bundle exec rake dv:migrate RAILS_ENV=test
  - ruby Itest test/models/usuario_test.rb
  - ruby Itest test/models/produto_test.rb
  - ruby Itest test/models/pedido_test.rb
  - ruby -S bundle exec cucumber --profile default

services:
  - postgresql